### ISSUE TITLE
build fails after following instructions

### ISSUE THREAD

**Issue by olilarkin** [brisklib/brisk-helloworld#1]
congratulations, this looks like it will be quite something!

unfortunately trying to compile this helloworld on macOS sonoma/x86_64 failed, something todo with vcpkg

here is what i did

```
git clone --recurse-submodules git@github.com:brisklib/brisk.git
git clone --recurse-submodules git@github.com:brisklib/brisk-helloworld.git
cd brisk-helloworld
mkdir build && cd build
cmake -DBRISK_DIR=~/Dev/brisk/ -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
```

[vcpkg-manifest-install.log](https://github.com/user-attachments/files/18189005/vcpkg-manifest-install.log)

**Comment by dancasarin** [comment]
Hi Oli,

Thank you for reporting this and for your kind words about my project. I appreciate your opinion.

The version of vcpkg automatically downloaded into `brisk-helloworld/vcpkg` (when no user-provided vcpkg was used) was outdated and did not match the requirements in `vcpkg.json`. A fix has been pushed to the `main` branch.

Please delete both `brisk-helloworld` and `brisk` directory, clone them again, and try running it once more.

**Comment by olilarkin** [comment]
that fixed it :-)
